server:
  port: 8000

spring:
  # Server mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: dduymen@gmail.com
    password: vcuw qnga gors vitw
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true

  datasource:
    password: menespostgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/mobile_v2?serverTimezone=UTC

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  #Oauth2
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1097604284267-ikgsv4k5p1lkbmivne2adnq1f3e6605m.apps.googleusercontent.com
            client-secret: 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
            scope:
              - openid
              - profile
              - email

logging:
  level:
    org:
      springframework:
        security: debug

# LOCKET
locket:
  app:
    name: Locket
    jwt:
      secretKey: c3ckfrhaKW8Mplm9ylgQCsMLoFmsip/ouP1u51eWRLRtCgDA6OFoLH+azJtNEDUYODPqhm/Kms2jYJdaIczcrap9vBVrbd7qMk1AuoNJjZg=
      expirationTimeMs: 1800000 # 30 minutes






